<?php

namespace papBundle\Repository;

/**
 * cambioPasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cambioPasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
