<?php

namespace papBundle\Repository;

/**
 * ModoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModoRepository extends \Doctrine\ORM\EntityRepository
{
}
