<?php

namespace papBundle\Repository;

/**
 * PasoProdEncargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasoProdEncargoRepository extends \Doctrine\ORM\EntityRepository
{
}
