papBundle\Entity\cambioPassword:
    type: entity
    table: null
    repositoryClass: papBundle\Repository\cambioPasswordRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        old:
            type: string
            length: 255
        new:
            type: string
            length: 255
        new2:
            type: string
            length: 255
    lifecycleCallbacks: {  }
